In [3]:
from surprise import KNNBasic, SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split
import numpy as np

In [4]:
data = Dataset.load_builtin('ml-100k', prompt=False)
raw_data = np.array(data.raw_ratings, dtype=int)

## Person correlation

In [6]:
X = [-2, -1, 0, 1, 2]
Y = [4, 1, 3, 2, 0]

In [7]:
np.corrcoef(X, Y)

array([[ 1. , -0.7],
       [-0.7,  1. ]])

In [8]:
np.corrcoef(X)

1.0

In [15]:
W = np.array([X, Y])

In [16]:
np.corrcoef(W)

array([[ 1. , -0.7],
       [-0.7,  1. ]])

In [17]:
W

array([[-2, -1,  0,  1,  2],
       [ 4,  1,  3,  2,  0]])

In [30]:
sig_x = lambda X: np.sqrt(np.mean(np.power(X - np.mean(X),2)))
sig_xy = lambda X, Y: np.mean(np.multiply(X-np.mean(X),Y-np.mean(Y)))
rho_xy = lambda X, Y: sig_xy(X,Y) / (sig_x(X)*sig_x(Y))

In [31]:
sig_x(X), sig_x(Y), sig_xy(X,Y), rho_xy(X,Y)

(1.4142135623730951, 1.4142135623730951, -1.4, -0.6999999999999998)