## Keras for Jax, 2022-1-10
- Basic numpy works for Keras while jax Numpy does not work for JAX

In [12]:
from jax import grad, jit, pmap
import jax.numpy as jnp
import numpy as np

In [13]:
import tensorflow as tf

In [14]:
layer = tf.keras.layers.Dense(2)

In [7]:
x = np.zeros((10,2))

In [8]:
y = layer(x)

In [9]:
y

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [15]:
x = jnp.zeros((10,5))
x

DeviceArray([[0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.]], dtype=float32)

In [16]:
layer(x)

AttributeError: 'tuple' object has no attribute 'rank'

In [19]:
y = tf.add(x,x)

In [20]:
y

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [22]:
grad(y, x)

TypeError: Expected a callable value, got [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [23]:
grad(lambda x: x+x,x)

TypeError: only integer scalar arrays can be converted to a scalar index

In [35]:
x = np.zeros((10,5))

In [36]:
L = lambda x: jnp.sum(2*x)

In [37]:
df = grad(L)

In [38]:
df(x)

DeviceArray([[2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.],
             [2., 2., 2., 2., 2.]], dtype=float32)

In [39]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
f = lambda x: tf.reduce_sum(x)

In [50]:
df = grad(f)
x = np.ones((2,))
f(x)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [51]:

df(x)

TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ConcreteArray([1. 1.], dtype=float32)>with<JVPTrace(level=2/0)> with
  primal = Traced<ConcreteArray([1. 1.], dtype=float32)>with<JaxprTrace(level=1/0)> with
    pval = (None, array([1., 1.]))
    recipe = *
  tangent = Traced<ShapedArray(float32[2])>with<JaxprTrace(level=1/0)> with
    pval = (ShapedArray(float32[2]), *)
    recipe = LambdaBinding()
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError