## 9장. 케라스2 응용
실제 문제에 인공지능을 활용할 때 생기는 문제들을 효율적으로 처리하는 케라스의 응용 기능을 알아봅시다.

### 9.3 실전에서 유용한 케라스 고급 기능
케라스의 유용한 고급 기능을 다룹니다.

In [20]:
# set to use CPU
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

import keras
keras.__version__

'2.4.3'

### 9.3.1 Lambda 계층
#### 9.3.1.1 파이썬 lambda를 함께 활용

In [21]:
from keras.layers import Lambda, Input, Concatenate
from tensorflow.keras.models import Model
import numpy as np

In [22]:
def Lambda_with_lambda():
    x = Input((2,))
    y = Lambda(lambda x: [x,x+2,x*2])(x)
    z = Concatenate()(y)
    m = Model(x, z)

    yp = m.predict_on_batch(np.array([[1,2],[3,4],[5,6]]))
    print(yp)
    
Lambda_with_lambda()

[[ 1.  2.  3.  4.  2.  4.]
 [ 3.  4.  5.  6.  6.  8.]
 [ 5.  6.  7.  8. 10. 12.]]


In [16]:
def Lambda_with_lambda_keras2():
    x = Input((2,))
    y = [x,x+2,x*2]
    z = Concatenate()(y)
    m = Model(x, z)

    yp = m.predict_on_batch(np.array([[1,2],[3,4],[5,6]]))
    print(yp)
    
Lambda_with_lambda_keras2()

[[ 1.  2.  3.  4.  2.  4.]
 [ 3.  4.  5.  6.  6.  8.]
 [ 5.  6.  7.  8. 10. 12.]]


In [26]:
from keras import backend as K
def Backend_for_Lambda():
    def kproc_concat(x):    
        m = K.mean(x, axis=1, keepdims=True)
        d1 = K.abs(x - m)
        d2 = K.square(x - m)
        return K.concatenate([x, d1, d2], axis=1)

    def kshape_concat(input_shape):
        output_shape = list(input_shape)
        output_shape[1] *= 3
        return tuple(output_shape)

    x = Input((3,))
    y = Lambda(kproc_concat, kshape_concat)(x)
    m = Model(x, y)

    yp = m.predict_on_batch(np.array([[1, 2, 3], [3, 4, 8]]))
    print(yp)
    
Backend_for_Lambda()

[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]]


In [32]:
import tensorflow as tf
def TF_for_Lamda():
    def kproc_concat(x):    
        m = tf.reduce_mean(x, axis=1, keepdims=True)
        d1 = tf.abs(x - m)
        d2 = tf.square(x - m)
        return tf.concat([x, d1, d2], axis=1)

    def kshape_concat(input_shape):
        output_shape = list(input_shape)
        output_shape[1] *= 3
        return tuple(output_shape)

    x = Input((3,))
    y = Lambda(kproc_concat, kshape_concat)(x)
    m = Model(x, y)

    yp = m.predict_on_batch(np.array([[1, 2, 3], [3, 4, 8]]))
    print(yp)
    
TF_for_Lamda()

[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]]


---
### 9.2.3 전체 코드

In [34]:
from keras.layers import Lambda, Input
from keras.models import Model

def Lambda_with_lambda():
    x = Input((1,))
    y = Lambda(lambda x: x + 1)(x)
    m = Model(x, y)

    yp = m.predict_on_batch(np.array([1, 2, 3]))
    print(yp)


def Lambda_function():
    def kproc(x):
        return x ** 2 + 2 * x + 1

    def kshape(input_shape):
        return input_shape

    x = Input((1,))
    y = Lambda(kproc, kshape)(x)
    m = Model(x, y)

    yp = m.predict_on_batch(np.array([1, 2, 3]))
    print(yp)

    
from keras import backend as K
def Backend_for_Lambda():
    def kproc_concat(x):    
        m = K.mean(x, axis=1, keepdims=True)
        d1 = K.abs(x - m)
        d2 = K.square(x - m)
        return K.concatenate([x, d1, d2], axis=1)

    def kshape_concat(input_shape):
        output_shape = list(input_shape)
        output_shape[1] *= 3
        return tuple(output_shape)

    x = Input((3,))
    y = Lambda(kproc_concat, kshape_concat)(x)
    m = Model(x, y)

    yp = m.predict_on_batch(np.array([[1, 2, 3], [3, 4, 8]]))
    print(yp)

    
import tensorflow as tf
def TF_for_Lamda():
    def kproc_concat(x):    
        m = tf.reduce_mean(x, axis=1, keepdims=True)
        d1 = tf.abs(x - m)
        d2 = tf.square(x - m)
        return tf.concat([x, d1, d2], axis=1)

    def kshape_concat(input_shape):
        output_shape = list(input_shape)
        output_shape[1] *= 3
        return tuple(output_shape)

    x = Input((3,))
    y = Lambda(kproc_concat, kshape_concat)(x)
    m = Model(x, y)

    yp = m.predict_on_batch(np.array([[1, 2, 3], [3, 4, 8]]))
    print(yp)


def main():
    print('Lambda with lambda')
    Lambda_with_lambda()

    print('Lambda function')
    Lambda_function()

    print('Backend for Lambda')
    Backend_for_Lambda()

    print('TF for Lambda')
    TF_for_Lamda()

main()

Lambda with lambda
np.array([1,2,3]) + 1:
[[2.]
 [3.]
 [4.]]
Lambda function
np.array([1,2,3]) + 1:
[[ 4.]
 [ 9.]
 [16.]]
Backend for Lambda
[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]]
TF for Lambda
[[1. 2. 3. 1. 0. 1. 1. 0. 1.]
 [3. 4. 8. 2. 1. 3. 4. 1. 9.]]
