In [2]:
using Pkg

In [3]:
Pkg.add("Flux")

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  99.9 %Fetching: [=====>                                   ]  10.4 %>                             ]  25.1 %Fetching: [==============>                          ]  34.4 %>                    ]  49.1 %>              ]  63.9 % [================================>        ]  78.8 %       ]  81.7 %

  Resolving package versions...
  Installed DiffResults ────────────────── v1.0.3
  Installed BinaryProvider ─────────────── v0.5.10
  Installed AbstractTrees ──────────────── v0.3.4
  Installed Flux ───────────────────────── v0.11.1
  Installed Colors ─────────────────────── v0.12.8
  Installed OrderedCollections ─────────── v1.4.1
  Installed NNlib ──────────────────────── v0.7.17
  Installed CEnum ──────────────────────── v0.4.1
  Installed TimerOutputs ───────────────── v0.5.13
  Installed CompilerSupportLibraries_jll ─ v0.3.4+0
  Installed LoopVectorization ──────────── v0.8.26
  Installed LLVM ───────────────────────── v2.0.0
  Installed ColorTypes ─────────────────── v0.11.0
  Installed TranscodingStreams ─────────── v0.9.6
  Installed DiffRules ──────────────────── v1.3.1
  Installed IRTools ────────────────────── v0.4.3
  Installed UnPack ─────────────────────── v1.0.2
  Installed Compat ─────────────────────── v3.39.0
  Installed StatsAPI ───────────────────── v1.0.0
  Instal

In [4]:
Pkg.add("MLDatasets")

  Resolving package versions...
  Installed Lz4_jll ───────── v1.9.2+2
  Installed NetworkOptions ── v1.2.0
  Installed LibSSH2_jll ───── v1.9.0+3
  Installed Blosc_jll ─────── v1.21.0+0
  Installed BinDeps ───────── v1.0.2
  Installed DataDeps ──────── v0.7.7
  Installed Zstd_jll ──────── v1.4.8+0
  Installed MLDatasets ────── v0.5.11
  Installed p7zip_jll ─────── v16.2.0+3
  Installed URIs ──────────── v1.3.0
  Installed HDF5_jll ──────── v1.12.0+1
  Installed GZip ──────────── v0.5.1
  Installed HDF5 ──────────── v0.15.6
  Installed Blosc ─────────── v0.7.0
  Installed URIParser ─────── v0.4.1
  Installed LibCURL_jll ───── v7.70.0+2
  Installed IniFile ───────── v0.5.0
  Installed PyCall ────────── v1.92.3
  Installed HTTP ──────────── v0.9.16
  Installed BufferedStreams ─ v1.0.0
  Installed nghttp2_jll ───── v1.40.0+2
  Installed MAT ───────────── v0.10.1
  Installed OpenSSL_jll ───── v1.1.1+6
######################################################################### 100.0%##O#- #  

In [5]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
x = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [7]:
x = rand(5, 3)

5×3 Array{Float64,2}:
 0.525118  0.668073  0.0659104
 0.516612  0.372276  0.506458
 0.674054  0.212838  0.195316
 0.951924  0.043865  0.959746
 0.95784   0.220842  0.914947

In [8]:
x = rand(BigFloat, 5, 3)

5×3 Array{BigFloat,2}:
 0.0775191  0.648122  0.164103
 0.615265   0.363389  0.962286
 0.090275   0.449237  0.337981
 0.931619   0.415767  0.931347
 0.783927   0.235849  0.232446

In [9]:
y = rand(Float32, 5, 3)

5×3 Array{Float32,2}:
 0.708388  0.566759  0.635116
 0.826746  0.295709  0.2982
 0.211264  0.99312   0.581531
 0.969746  0.701121  0.186995
 0.132967  0.808198  0.261864

In [10]:
length(x)

15

In [11]:
size(x)

(5, 3)

In [12]:
x

x[2,3]

0.962286154384433450902992834569414578290998182918475709307940755058484463721186

In [13]:
x

5×3 Array{BigFloat,2}:
 0.0775191  0.648122  0.164103
 0.615265   0.363389  0.962286
 0.090275   0.449237  0.337981
 0.931619   0.415767  0.931347
 0.783927   0.235849  0.232446

In [16]:
zeros(5,5) .+ (1:5)'

5×5 Array{Float64,2}:
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0

In [20]:
(1:5) .+ 1

2:6

In [21]:
W = randn(5, 10)
x = rand(10)
W*x

5-element Array{Float64,1}:
 -1.7441688143614578
 -2.637730297016099
  1.6117730218129178
 -1.0293704136961424
 -1.627350430697382

In [25]:
using CUDA

┌ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]
└ @ Base loading.jl:1260


In [23]:
import Pkg

In [24]:
Pkg.add("CUDA")

  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [052768ef] + CUDA v1.3.3
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]


In [26]:
x = cu(rand(5,3))

┌ Error: Could not initialize CUDA
│   exception = (CuError(CUDA.CUDA_ERROR_NO_DEVICE, nothing), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007f3d481d4fde, Ptr{Nothing} @0x00007f3d481df098, Ptr{Nothing} @0x00007f3d4820094e, Ptr{Nothing} @0x00007f3d481dd64e, Ptr{Nothing} @0x00007f3d481dd7d4, Ptr{Nothing} @0x00007f3d481d49d1, Ptr{Nothing} @0x00007f3d481d4ad8, Ptr{Nothing} @0x00007f3d481dcea9, Ptr{Nothing} @0x00007f3d481dd1a7, Ptr{Nothing} @0x00007f3d481dcd80, Ptr{Nothing} @0x00007f3d481dcdf2, Ptr{Nothing} @0x00007f3d481dab21, Ptr{Nothing} @0x00007f3d481dc1a4, Ptr{Nothing} @0x00007f3d481d490b, Ptr{Nothing} @0x00007f3d8134b75b, Ptr{Nothing} @0x00007f3d8134b389, Ptr{Nothing} @0x00007f3d8134b8f0, Ptr{Nothing} @0x00007f3d8134c9c8, Ptr{Nothing} @0x00007f3d8134d616, Base.InterpreterIP in top-level CodeInfo for Main at statement 1, Ptr{Nothing} @0x00007f3d81365e08, Ptr{Nothing} @0x00007f3d81366f20, Ptr{Nothing} @0x00007f3d481ccef5, Ptr{Nothing} @0x00007f3d481cb83e, Ptr{Nothing} @0

AssertionError: AssertionError: CUDA.jl did not successfully initialize, and is not usable.

In [27]:
f(x) = 3x^2 + 2x + 1
f(5)

86

In [28]:
using Flux: gradient

┌ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
└ @ Base loading.jl:1260
  likely near /home/sjkim/.julia/packages/Zygote/ggM8Z/src/compiler/chainrules.jl:46
  likely near /home/sjkim/.julia/packages/Zygote/ggM8Z/src/compiler/chainrules.jl:46


In [29]:
df(x) = gradient(f, x)[1]

df (generic function with 1 method)

In [30]:
df(5)

32