In [1]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [2]:
x = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [3]:
x = rand(5, 3)

5×3 Matrix{Float64}:
 0.415226    0.0393616  0.43124
 0.78459     0.223017   0.388901
 0.00274258  0.679509   0.664541
 0.37711     0.706439   0.795659
 0.400812    0.697554   0.191403

In [4]:
x = rand(BigFloat, 5, 3)

5×3 Matrix{BigFloat}:
 0.663993  0.102082  0.226118
 0.316006  0.824894  0.349097
 0.781762  0.420398  0.584504
 0.958804  0.85871   0.289992
 0.161512  0.263538  0.847835

In [5]:
y = rand(Float32, 5, 3)

5×3 Matrix{Float32}:
 0.0783666  0.352056  0.404717
 0.451754   0.608688  0.246153
 0.442941   0.536135  0.110991
 0.150189   0.281312  0.130321
 0.972858   0.943427  0.380493

In [6]:
length(x)

15

In [7]:
size(x)

(5, 3)

In [8]:
x

x[2,3]

0.3490968069518976826393417605330958413173987045304930094147391342303718829399885

In [9]:
x

5×3 Matrix{BigFloat}:
 0.663993  0.102082  0.226118
 0.316006  0.824894  0.349097
 0.781762  0.420398  0.584504
 0.958804  0.85871   0.289992
 0.161512  0.263538  0.847835

In [10]:
zeros(5,5) .+ (1:5)'

5×5 Matrix{Float64}:
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0
 1.0  2.0  3.0  4.0  5.0

In [11]:
(1:5) .+ 1

2:6

In [12]:
W = randn(5, 10)
x = rand(10)
W*x

5-element Vector{Float64}:
  1.557993634788684
  2.1914512753327475
  0.33738438653281644
 -2.7942889052437248
  1.5223272295391495

In [13]:
using CUDA

LoadError: ArgumentError: Package CUDA not found in current path:
- Run `import Pkg; Pkg.add("CUDA")` to install the CUDA package.


In [14]:
import Pkg

In [15]:
Pkg.add("CUDA")

    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed LogExpFunctions ─ v0.3.3
   Installed Reexport ──────── v1.2.2
   Installed AbstractFFTs ──── v1.0.1
   Installed Random123 ─────── v1.4.2
   Installed ChainRulesCore ── v1.7.2
   Installed GPUArrays ─────── v8.1.1
   Installed OpenSpecFun_jll ─ v0.5.5+0
   Installed LLVMExtra_jll ─── v0.0.11+0
   Installed LLVM ──────────── v4.6.0
   Installed Adapt ─────────── v3.3.1
   Installed BFloat16s ─────── v0.1.0
   Installed GPUCompiler ───── v0.12.9
   Installed RandomNumbers ─── v1.5.3
   Installed CUDA ──────────── v3.4.2
    Updating `~/.julia/environments/v1.6/Project.toml`
  [052768ef] + CUDA v3.4.2
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [621f4979] + AbstractFFTs v1.0.1
  [79e6a3ab] + Adapt v3.3.1
  [ab4f0b2a] + BFloat16s v0.1.0
  [fa961155] + CEnum v0.4.1
  [052768ef] + CUDA v3.4.2
  [d360d2e6] + 

In [17]:
using CUDA
x = cu(rand(5,3))

5×3 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 0.783003  0.722556  0.36107
 0.67666   0.875749  0.622902
 0.84795   0.666693  0.492653
 0.808512  0.633906  0.17664
 0.501955  0.564222  0.905869

In [18]:
f(x) = 3x^2 + 2x + 1
f(5)

86

In [20]:
using Flux: gradient

In [21]:
df(x) = gradient(f, x)[1]

df (generic function with 1 method)

In [22]:
df(5)

32.0